########### build container
FROM node:24 AS phoneticsbuild
WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY tsconfig.json ./
ADD src/ ./src/
RUN npm run build
RUN ls -l

########### deployment container
FROM node:24
WORKDIR /app

RUN git clone https://github.com/ZalozbaDev/speech_recognition_corpus_creation.git
RUN cd speech_recognition_corpus_creation && git checkout 68596c9384adfd073aefc84ee5c0f4393b04b1b5
RUN mv speech_recognition_corpus_creation dist/

RUN apt update
RUN apt install -y python3-numpy python3-yaml

COPY package*.json ./
RUN npm ci --omit=dev

COPY --from=phoneticsbuild /app/dist ./dist

RUN mkdir -p uploads

RUN mkdir -p src/scripts
COPY src/scripts/create_dictionary.sh src/scripts

ENV NODE_ENV=production
ENV PORT=3000

EXPOSE 3000

ENV SERVER_MODE=FONETISIKI_SLOWNIK

CMD ["node", "dist/index.js"]
